### ISSUE TITLE
Error on running subsegment on Ubuntu 14.04

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#356]
`boolean error`. Reported by Mark Metz, USDA, Smithsonian.

**Comment by quicklizard99** [comment]
```
Error in WorkerThread.run
Traceback (most recent call last):
  File "/home/mark/Projects/Inselect/inselect-0.1.34/inselect/gui/worker_thread.py", line 64, in run
    self._operation(self.progress)
  File "/home/mark/Projects/Inselect/inselect-0.1.34/inselect/gui/plugins/subsegment.py", line 52, in __call__
    self.document, self.row, seeds, callback=progress
  File "/home/mark/Projects/Inselect/inselect-0.1.34/inselect/lib/segment_document.py", line 98, in subsegment
    new_items = sort_document_items(new_items, self.sort_by_columns)
  File "/home/mark/Projects/Inselect/inselect-0.1.34/inselect/lib/sort_document_items.py", line 45, in sort_document_items
    y_bins = _do_kde(r.y_centre for r in rects)
  File "/home/mark/Projects/Inselect/inselect-0.1.34/inselect/lib/sort_document_items.py", line 27, in _do_kde
    bins = np.append(samples[minima], RESCALE)
IndexError: arrays used as indices must be of integer (or boolean) type
MainWindow.worker_finished False An error occurred:
arrays used as indices must be of integer (or boolean) type
```

**Comment by quicklizard99** [comment]
Unable to recreate on my Ubuntu 14.04 vm.

The transition to Python 3 (#95 #403) means that from 0.1.35 onwards, Inselect will be run using a consistent environment (using Anaconda), so I expect this problem to disappear.
