### ISSUE TITLE
OpenCV Error when subsegmenting

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#370]
Open image from NRM `homogenous background-boxes randomly oriented.tif` - click on two objects in box 5 and subselect:

``` 
OpenCV Error: Assertion failed (!bgdSamples.empty() && !fgdSamples.empty()) in initGMMs, file /Users/user/miniconda3/conda-bld/work/opencv-2.4.12/modules/imgproc/src/grabcut.cpp, line 379
Error in WorkerThread.run
Traceback (most recent call last):
  File "/Users/lawh/projects/inselect/inselect/gui/worker_thread.py", line 64, in run
    self._operation(self.progress)
  File "/Users/lawh/projects/inselect/inselect/gui/plugins/subsegment.py", line 52, in __call__
    self.document, self.row, seeds, callback=progress
  File "/Users/lawh/projects/inselect/inselect/lib/segment_document.py", line 85, in subsegment
    rects, display = segment_grabcut(img.array, window, seeds)
  File "/Users/lawh/projects/inselect/inselect/lib/segment.py", line 376, in segment_grabcut
    cv2.grabCut(image, mask, rect, bgmodel, fgmodel, 1, cv2.GC_INIT_WITH_MASK)
error: /Users/user/miniconda3/conda-bld/work/opencv-2.4.12/modules/imgproc/src/grabcut.cpp:379: error: (-215) !bgdSamples.empty() && !fgdSamples.empty() in function initGMMs

MainWindow.worker_finished False An error occurred:
/Users/user/miniconda3/conda-bld/work/opencv-2.4.12/modules/imgproc/src/grabcut.cpp:379: error: (-215) !bgdSamples.empty() && !fgdSamples.empty() in function initGMMs
```

**Comment by quicklizard99** [comment]
Not fixed by transition to OpenCV 3 (#391).
