### ISSUE TITLE
Ugly error message when opening file with ascii characters in name

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#371]
```
Traceback (most recent call last):
  File "inselect/gui/utils.py", line 113, in wrapper
  File "inselect/gui/main_window.py", line 280, in open_file
  File "site-packages/pathlib.py", line 936, in __new__
  File "site-packages/pathlib.py", line 613, in _from_parts
  File "site-packages/pathlib.py", line 606, in _parse_args
  File "site-packages/pathlib.py", line 75, in parse_parts
  File "site-packages/pathlib.py", line 58, in _py2_fsencode
UnicodeEncodeError: 'ascii' codec can't encode character u'\u030a' in position 77: ordinal not in range(128)
```

**Comment by quicklizard99** [comment]
`pathlib` does not play nicely with unicode on Python 2. Revisit this once we have moved to Python 3 (#95 #339 )

**Comment by quicklizard99** [comment]
#403 fixes this for Mac OS X and Linux. Remains broken for Windows due to defect in OpenCV. See https://github.com/opencv/opencv/issues/4242 and https://github.com/opencv/opencv/issues/4292
