### ISSUE TITLE
memory error on windows

### ISSUE THREAD

**Issue by aliceh75** [NaturalHistoryMuseum/inselect#38]
Reproduce:
---------------
- Open the test image
- Click on segment
- Re-Open the test image
- Click on segment

Result:
----------
```
Traceback (most recent call last):
  File "C:\Users\alich2\Anaconda\src\inselect\inselect\image_viewer.py", line 76, in run
    size_filter=0)
  File "C:\Users\alich2\Anaconda\src\inselect\inselect\segment.py", line 196, in segment_edges
    mask = remove_lines(image)
  File "C:\Users\alich2\Anaconda\src\inselect\inselect\segment.py", line 114, in remove_lines
    mag2 = (255*mag/np.max(mag)).astype(np.uint8)
MemoryError
```

**Comment by quicklizard99** [comment]
As far as I know, nobody has seen this error since Inselect was altered to segment image thumbnails, including on 32-bit machines.
